CREATE TABLE IF NOT EXISTS "groups" (
	"id" INTEGER NOT NULL,
	"key" TEXT NOT NULL UNIQUE,
	"password" TEXT NOT NULL,
	"drafted" BOOLEAN NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "users" (
	"id" INTEGER NOT NULL,
	"username" TEXT NOT NULL UNIQUE,
	"email" TEXT,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "user_group_membership" (
	"id" INTEGER NOT NULL,
	"groupID" INTEGER NOT NULL,
	"userID" INTEGER NOT NULL,
	"role" TEXT NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("userID") REFERENCES "users"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("groupID") REFERENCES "groups"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
